services:
  backend:
    build: .   # backend se pokreće preko Dockerfile
              # unutar trenutnog direktorija
    ports:
      - '5000:5000'  # PC komunicira s kontejnerom
    environment:
      - NODE_ENV=staging      # KRITIČNO: Kaže Knexu da koristi PostgreSQL
      - DB_HOST=db            # KRITIČNO: Adresa baze unutar Docker mreže
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=my_secret
      - DB_NAME=sceduly_db
      - JWT_SECRET=neki_secret
      - REDIS_HOST=redis       # KRITIČNO: Adresa Redis servisa unutar Docker mreže
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: sceduly_db
    ports:
      - '5434:5432' # <--- NOVO MAPIRANJE PORTA: Host 5434 -> Kontejner 5432
    volumes:  # podaci baze će biti trajno pohranjeni u volume
      - sceduly_db_data:/var/lib/postgresql

  redis:
    image: redis:latest
    ports:
      - '6379:6379'  # PC komunicira s Redis kontejnerom

volumes:  # volume za trajnu pohranu PostgreSQL podataka
  sceduly_db_data:
